sudo: false
language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "4"
  - "5"

env:
  global:
  - SAUCE_USERNAME: karmarunnerbot
  - secure: "bRVY+hYZwMf1SqVnMyZRJTLD0gN1hLx9/MwO8MM/qBiu3YNjXy49XElfMdzMKN6cZeKTmhcnjmZonbJuI1PQ2t+utGkyjnlVLJ/OlWptreKLzIlcbt4hrdPoTcjmUTwDWq9Ex9cVoYX8AzCasETttpczp3P+s3+vmOUj8z25JyU="
  - CXX=g++-4.8

# Make sure we have a new npm on Node 0.10. npm >= 2 should work so by not updating them
# here we have proper version coverage, especially that most people use the npm version
# that's included in a Node version they use.
before_install:
  - '[ "${TRAVIS_NODE_VERSION}" != "0.10" ] || npm install -g npm'
  - npm config set loglevel warn
  - g++-4.8 --version

addons:
  firefox:
    "latest"
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm run init
  - export $(openssl aes-256-cbc -pass env:CREDENTIALS_PASS -d -in credentials)

script:
  - npm run travis
