sudo: false
language: node_js
node_js:
  - 10
  - 12

env:
  global:
  - SAUCE_USERNAME: karmarunnerbot
  - secure: "bRVY+hYZwMf1SqVnMyZRJTLD0gN1hLx9/MwO8MM/qBiu3YNjXy49XElfMdzMKN6cZeKTmhcnjmZonbJuI1PQ2t+utGkyjnlVLJ/OlWptreKLzIlcbt4hrdPoTcjmUTwDWq9Ex9cVoYX8AzCasETttpczp3P+s3+vmOUj8z25JyU="
  - CXX=g++-4.8
matrix:
  fast_finish: true
  include:
    - name: "Lint code and commit message format"
      node_js: "10"
      env: VALIDATE_COMMIT_MSG=true LINT=true

before_install:
  - npm config set loglevel warn
  - g++-4.8 --version

addons:
  firefox:
    "latest"
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

services:
  - xvfb

before_script:
  - npm run init
  - export $(openssl aes-256-cbc -pass env:CREDENTIALS_PASS -d -in credentials)
  - echo "TRAVIS_COMMIT $TRAVIS_COMMIT"
  - echo "TRAVIS_PULL_REQUEST_SHA $TRAVIS_PULL_REQUEST_SHA"
  - COMMIT_TO_VALIDATE=${TRAVIS_PULL_REQUEST_SHA:-$TRAVIS_COMMIT}
  - echo "COMMIT_TO_VALIDATE $COMMIT_TO_VALIDATE"
  - 'if [ "$VALIDATE_COMMIT_MSG" == "true" ]; then ./scripts/validate-commit-msg.sh $COMMIT_TO_VALIDATE; fi'
  - 'if [ "$LINT" == "true" ]; then npm run lint; fi'

script:
  - npm run travis

after_success:
  # run automated release process with semantic-release
  - if [[ "$TRAVIS_BRANCH" == "master" && "$TRAVIS_EVENT_TYPE" == "push" && "$TRAVIS_NODE_VERSION" == "12" ]]; then
      npm i --no-save semantic-release@15 @semantic-release/changelog@3 @semantic-release/git@7;
      semantic-release;
    fi;