language: node_js
node_js:
  - 0.8
  - 0.10

before_install:
  - mkdir node_modules
  - ln -s .. node_modules/karma

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm link
  - npm install -g grunt-cli

script:
  - grunt
