language: node_js
node_js:
  - "0.10"
  - "0.8"

env:
  global:
  - SAUCE_USERNAME: vojtajina
  - secure: "bRVY+hYZwMf1SqVnMyZRJTLD0gN1hLx9/MwO8MM/qBiu3YNjXy49XElfMdzMKN6cZeKTmhcnjmZonbJuI1PQ2t+utGkyjnlVLJ/OlWptreKLzIlcbt4hrdPoTcjmUTwDWq9Ex9cVoYX8AzCasETttpczp3P+s3+vmOUj8z25JyU="

# Make sure we have new NPM.
before_install:
  - npm install -g npm
  - npm config set loglevel warn

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g grunt-cli
  - rm -rf node_modules/karma
  - export $(openssl aes-256-cbc -pass env:CREDENTIALS_PASS -d -in credentials)

script:
  - ./scripts/travis_run.sh

after_success:
  - ./scripts/presubmit.sh
